cask_args appdir: "/Applications"

tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
# tap "homebrew/cask-drivers"
tap "buo/cask-upgrade"

cask "discord"
cask "firefox"
cask "iterm2"
cask "karabiner-elements"
cask "macs-fan-control"
cask "obs"
cask "obsidian"
cask "proxyman"
cask "signal"
cask "skype"
cask "vagrant"
cask "via"
cask "visual-studio-code"
cask "vlc"

brew "bat"
brew "coreutils"
brew "curl"
brew "exiftool"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "glow"
brew "git-delta"
brew "htop"
brew "imagemagick"
brew "jc"
brew "jq"
brew "neofetch"
brew "node"
brew "pandoc"
brew "pyenv"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "neovim"
brew "wget"
