name: default
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - jupyter
  - matplotlib
  - plotly
  - pandas
  - mypy
  - pip
  - pylint
  - pytorch
  - requests
  - scipy
  - scikit-learn
  - torchvision
  - rich
  - tqdm
  - pip:
    - wget
    - einops
    - pytorch-lightning
    - manim
    - hydra-core
    - omegaconf
    - wandb
