name: default
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - plotly
  - pandas
  - pip
  - pytorch
  - requests
  - scipy
  - scikit-learn
  - torchvision
  - tqdm
  - pip:
    - wget
    - hydra-core
    - omegaconf
