# Bar customisation
set-option -g status-style bg=default,fg=white
set-option -g status-left ' '
set-option -g status-left-length 1
set-option -g status-right '#[fg=white]@#{session_name}'
set-option -g window-status-format '#[fg=#b4637a]#{window_index}#[fg=white]:#{window_name}#{window_flags}'
set-option -g window-status-current-format '#[bold,fg=#56949f]#{window_index}#[bold,fg=white]:#{window_name}#{window_flags}'
set-window-option -g mode-style bg=#56949f,fg=black
set -g message-style bg=#b4637a,fg=black

# Open new pane in cwd
bind-key c new-window -c '#{pane_current_path}'
bind-key x kill-pane

# Enable mouse support
set -g mouse on

# Set leader
unbind C-b
set -g prefix M-j
bind M-j send-prefix

# Renumber windows
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Title setting
set-option -g set-titles on
set-option -g set-titles-string '#{window_index}:#{pane_current_command}'
set-option -g automatic-rename on
set-option -g status-interval 5
set -s command-alias rest='setw automatic-rename'

# tmux-sensible
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 2500000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Upgrade $TERM
set -g default-terminal "xterm-256color"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Easier and faster switching between next/prev window
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
