# live_config_reload = true

general.import = [
    "zenbones.toml",
    "keybindings.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "PragmataPro Mono" }
offset = { x = 0, y = 7 }
size = 16

[mouse]
hide_when_typing = true

[window]
blur = true
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.9
option_as_alt = "OnlyLeft"
padding = { x = 5, y = 2 }

