[keyboard]
bindings = [
    { key = "1", mods = "Command|Super", chars = "\u0001\u0031" },
    { key = "2", mods = "Command|Super", chars = "\u0001\u0032" },
    { key = "3", mods = "Command|Super", chars = "\u0001\u0033" },
    { key = "4", mods = "Command|Super", chars = "\u0001\u0034" },
    { key = "5", mods = "Command|Super", chars = "\u0001\u0035" },
]
