export DOTFILES=~/dotfiles
export ZSH=$DOTFILES/zsh/oh-my-zsh
export PATH=~/--PATH--TO--CONDA--/bin:$PATH

ZSH_THEME="materialshelloceanic"

source $ZSH/oh-my-zsh.sh
source $ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $DOTFILES/alias/aalto
source $DOTFILES/alias/git
source $DOTFILES/alias/misc
